### ISSUE TITLE
Add configuration option for indicator position

### ISSUE THREAD

**Issue by jwilsson** [lee-dohm/indentation-indicator#12]
Hi,
I'd like to propose a new setting for controlling the indicator position, i.e. placing it to the left or to the right together with other file info, such as encoding etc.

I'd be more than happy to submit a PR for it, just wanted to see if there's any intrest in it.

**Comment by lee-dohm** [comment]
A pull request would be fine :grinning:

**Comment by lee-dohm** [comment]
Forgot to close this when the PR was merged.
