### ISSUE TITLE
change indentation with right click menu

### ISSUE THREAD

**Issue by schmurfy** [lee-dohm/indentation-indicator#14]
I am not sure if it is even possible with Atom API but it would be nice to be able to quickly switch settings for active buffer by right clicking the indicator like sublime does.

**Comment by lee-dohm** [comment]
When the indentation mechanisms are improved (see atom/atom#3719) then this could be accomplished, but I would use left-click like the other status-bar indicators in Atom.

**Comment by schmurfy** [comment]
nice, left click is fine and I just realized that is what sublime uses too ^^

**Comment by forivall** [comment]
It looks like atom/atom#3719 has been solved by atom/atom#8356. Have you looked into solving this, or would you be open to a pull request?

Notes:
* https://atom.io/docs/api/v1.1.0-beta.0/TextEditor#instance-setSoftTabs
* https://atom.io/docs/api/v1.1.0-beta.0/TextEditor#instance-setTabLength

**Comment by lee-dohm** [comment]
I have looked into it somewhat but things have gotten busy in my
personal life and haven't been able to pursue it further. So I would be
open to a pull request if someone wants to tackle this. 

On 2015-10-01 14:33, Jordan Klassen wrote: 

> It looks like atom/atom#3719 [1] has been solved by atom/atom#8356 [2]. Have you looked into solving this, or would you be open to a pull request? 
> 
> Notes: 
> 
> * https://atom.io/docs/api/v1.1.0-beta.0/TextEditor#instance-setSoftTabs [3]
> * https://atom.io/docs/api/v1.1.0-beta.0/TextEditor#instance-setTabLength [4]
> 
> --
> Reply to this email directly or view it on GitHub [5].
 

Links:
------
[1] https://github.com/atom/atom/issues/3719
[2] https://github.com/atom/atom/pull/8356
[3]
https://atom.io/docs/api/v1.1.0-beta.0/TextEditor#instance-setSoftTabs
[4]
https://atom.io/docs/api/v1.1.0-beta.0/TextEditor#instance-setTabLength
[5]
https://github.com/lee-dohm/indentation-indicator/issues/14#issuecomment-144856376

**Comment by schmurfy** [comment]
I switched to tab-control which pretty much does what this plugin does but also adds the ability to select tab width when clicking the indicator.

**Comment by andradei** [comment]
tab-control uses @lee-dohm's [tabs-to-spaces](https://github.com/lee-dohm/tabs-to-spaces) to perform the action this issue is pointing out. Interesting...
