### ISSUE TITLE
Indention Indication Wrong On File Open

### ISSUE THREAD

**Issue by bobrocke** [lee-dohm/indentation-indicator#15]
When I first open a file, the indentation indication at the bottom of the window is wrong. Once I switch to another tab, and back, it corrects itself.

**Comment by lee-dohm** [comment]
Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?

Also, can you give specific repro steps and information on your configuration? I cannot reproduce the issue you're mentioning.

**Comment by bobrocke** [comment]
Atom v1.0.9
Mac OS X 10.10.5

I opened a .scss file and the indication was Tabs:2 - incorrect. I switched to another tab, switched back, and the indication was Tabs:3 - correct.

Tabs:3 was set in the `.editorconfig` file.

**Comment by lee-dohm** [comment]
What is Atom configured to use for SCSS files?

**Comment by bobrocke** [comment]
Tabs:2

**Comment by lee-dohm** [comment]
So indentation-indicator is correct ... when the file is opened, it is set to Tabs:2. It is just that editorconfig changes it out from under indentation-indicator.

**Comment by lee-dohm** [comment]
I'll look to see if there are new events that indentation-indicator can hook into, but if there isn't ... this may be the best that can be done.

**Comment by bobrocke** [comment]
Hmmm. So editorconfig doesn't set the indentation when the file is opened?

The indention works as I intend right after opening the file. I hit a tab and get a 3-space tab. The indication continues to show Tabs:2 even though I just got a Tabs:3!

**Comment by bobrocke** [comment]
Can indention-indicator check again a second or two after a window is opened to get what .editorconfig sets?

**Comment by lee-dohm** [comment]
editorconfig probably hooks into the same file-open observation event that indentation-indicator does. But if indentation-indicator gets notified first, then editorconfig hasn't changed anything yet.

> Can indention-indicator check again a second or two after a window is opened to get what .editorconfig sets?

No, I'm not going to special case the code just for editorconfig.

**Comment by bobrocke** [comment]
Is not editorconfig a fairly common package? Or do people set their preferred indentation with Atom's settings and commit that file to Git so that a team all uses the same settings?

**Comment by lee-dohm** [comment]
> Is not editorconfig a fairly common package?

> Or do people set their preferred indentation with Atom's settings and commit that file to Git so that a team all uses the same settings?

What do either of these have to do with anything?

**Comment by bobrocke** [comment]
They have to do with how many people use .editorconfig with Atom and how important it would be to them for indentation-indicator to accommodate their use case. That's all.

**Comment by lee-dohm** [comment]
I'm not going to work around editorconfig's bug. If it wants to integrate with the Atom API in a way that works the way everything else does, that would be great.
