### ISSUE TITLE
Detects indentation based on comments

### ISSUE THREAD

**Issue by Stanzilla** [lee-dohm/indentation-indicator#17]
I have a lua file here that starts with a few comments that are indented with 3 spaces while the remaining file (actual code) is indented with 4 spaces. Your package reports 3 spaces as indentation of the file, is there a way the detection could be changed to ignore comments?

**Comment by lee-dohm** [comment]
My package reports what Atom has set for the active `TextEditor`. If you want Atom to autodetect indentation differently, it should probably be reported on https://github.com/atom/atom.

Thanks for using the package :grinning:
